### ISSUE TITLE
'Fake' scales: Purpose and support in eatCodebook 

### ISSUE THREAD

**Issue by beckerbenj** [beckerbenj/eatCodebook#7]
What was the original purpose of 'fake' scales? 

`layout.skala.fake()` and `kennwerte.skala.fake()` exist and a layout number (`9`) is assigned. However, there is no original documentation (no comments, no mention in .doc documentation.

Currently, support is lacking for the following functions:
- `createScaleInfo()`
- `inferLayout()`
- maybe `codebook()`?

**Comment by beckerbenj** [comment]
Support may also be lacking for `createInputForDescriptives()` and `calculateDescriptives()`; will discuss this with @weirichs .

**Comment by beckerbenj** [comment]
Start by implementing fake scales for `createInputForDescriptives()` and `calculateDescriptives()`. In the end, the following code should run without problems and generating descriptives for a `skala_fake` scale (see proper scale `skala1` for comparison): 

```
clean2 <- eatGADS::import_spss("tests/testthat/helper_clean2.sav")
clean_input2 <- createInputForDescriptives(clean2)
calculateDescriptives(clean, inputForDescriptives = clean_input)
```

For string intersects, see https://stackoverflow.com/questions/28261825/longest-common-substring-in-r-finding-non-contiguous-matches-between-the-two-str

**Comment by weirichs** [comment]
Um Missverständnisse zu vermeiden, hier das bisherige Vorgehen zur Identifikation "richtiger" Skalen und das vorgeschlagene Vorgehen zur Identifikation von "fake"-Skalen: 

**richtige Skalen**:

- as

**Comment by beckerbenj** [comment]
Mh, alternativ könnte ich mir vorstellen, dass Fake-Skalen auch gar nicht automatisiert erkannt werden müssten? Das ist ja auch eine Eingabe, die die Anwender:innen selbst vornehmen können. Sogar die Skalen-Identifikation ist ja schon sehr grenzwertig...
Dann würde man in der Dokumentation explizit erwähnen, dass Fake-Skalen nicht automatisiert erkannt werden und händisch eingetragen werden müssen. Fände ich gar nicht so verkehrt, da es das ja im BT auch nicht gibt und wir deshalb keinen vernünftigen/angemessenen Default eintragen können?

Außerdem wäre das ja auch keine Entscheidung für die Ewigkeit. Falls einem da noch etwas Vernünftiges einfällt, könnte man das a) als separate Funktion nachschalten oder b) auch noch in `createInputForDescriptives()` nachimplementieren.

**Comment by weirichs** [comment]
Wenn man aber sagt, dass Fake-Skalen nicht automatisch erkannt werden müssen, dann stellt sich die Frage, wie der user sie (von Hand) spezifizieren soll. Denn `createInputForDescriptives` muss ja am Ende einen Output liefern, in dem Fake-Skalen als solche identifiziert sind (allein weil `calculateDescriptives` diese Skalen anders behandeln muss als richtige Skalen). Also müsste `createInputForDescriptives`, das ja nur einen schlichten `data.frame` zurückgibt, seinerseits vom user bereits einen `data.frame` bekommen, der die Zuordnung enthält, welche Items zu welcher fake-Skala gehören. Das finde ich irgendwie ungünstig, weil unintuitiv und umständlich. 

Ich fände es besser, lieber jetzt eine konzeptuell einigermaßen saubere Zuordnung zu überlegen, anstatt was provisorisches zusammen zu stricken und zu hoffen, dass einem irgendwann was Vernünftiges einfällt.

**Comment by beckerbenj** [comment]
Auf jeden Fall, ein händisches Schema müsste man festlegen und in der Dokumentation auch beschreiben. Ich denke das wäre aber auch einfacher für den User, dann im `createInputForDescriptives()` diese Änderungen vorzunehmen, als vorher einen entsprechenden `data.frame` basteln zu müssen. 

Ich denke man muss an der Stelle auch ehrlich sein, in wie fern die Bestimmung der ganzen Variablentypen über Benennungs- oder Label-Schemata in der Praxis möglich ist: Denke nur so halbwegs. Man führt über diese Schiene ja auch sehr starke Konventionen ein, die Nutzende theoretisch bei der Benennung/Labelung von Variablen befolgen müssen.

Würde vorschlagen, wir sprechen dazu morgen mal!

**Comment by beckerbenj** [comment]
Take-away:
- `createInputForDescriptives()` soll keine Fake-Skalen erkennen können (wäre zu krude).
- Fake-Skalen sind daran erkennbar, dass sie eine gemeinsame `group`-Variable haben (Skalen-Name) und unter `type` überall `item` steht
- Letzteres wird auch für reguläre Skalen nachimplementiert (sowohl in `createInputForDescriptives()` als auch in `calculateDescriptives()`
